package types

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *AccountAndInputData) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "AccountAddress":
			z.AccountAddress, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "AccountAddress")
				return
			}
		case "InputData":
			z.InputData, err = dc.ReadBytes(z.InputData)
			if err != nil {
				err = msgp.WrapError(err, "InputData")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *AccountAndInputData) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "AccountAddress"
	err = en.Append(0x82, 0xae, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	if err != nil {
		return
	}
	err = en.WriteString(z.AccountAddress)
	if err != nil {
		err = msgp.WrapError(err, "AccountAddress")
		return
	}
	// write "InputData"
	err = en.Append(0xa9, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.InputData)
	if err != nil {
		err = msgp.WrapError(err, "InputData")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *AccountAndInputData) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "AccountAddress"
	o = append(o, 0x82, 0xae, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73)
	o = msgp.AppendString(o, z.AccountAddress)
	// string "InputData"
	o = append(o, 0xa9, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61)
	o = msgp.AppendBytes(o, z.InputData)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *AccountAndInputData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "AccountAddress":
			z.AccountAddress, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "AccountAddress")
				return
			}
		case "InputData":
			z.InputData, bts, err = msgp.ReadBytesBytes(bts, z.InputData)
			if err != nil {
				err = msgp.WrapError(err, "InputData")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *AccountAndInputData) Msgsize() (s int) {
	s = 1 + 15 + msgp.StringPrefixSize + len(z.AccountAddress) + 10 + msgp.BytesPrefixSize + len(z.InputData)
	return
}
